### PR TITLE
Remove Cake.Tfs addin since it is deprecated

### PR DESCRIPTION
**Pull request by pascalberger**
Remove Cake.Tfs addin since it is deprecated

### CODE REVIEW

**Comment by pascalberger** [comment]
@Jericho https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/96 is already released (not that Addin Discoverer will add it again once removed)?

**Comment by Jericho** [comment]
Not only will AddinDisco NOT add a YAML file for this addin but also it will also suggest to delete the YAML file during the next schedule build (which is midnight UTC) so there is no need to manually delete the YAML file.

**Comment by pascalberger** [comment]
> Not only will AddinDisco NOT add a YAML file for this addin but also it will also suggest to delete the YAML file during the next schedule build (which is midnight UTC) so there is no need to manually delete the YAML file.

Oh, nice. That would have been my next suggestion otherwise :)

@Jericho You sure it is working as expected? Because I marked it as deprecated over 24 hours ago. 

If you want to use this as a test case I can also delete the PR and let addin discoverer do its magic.

**Comment by Jericho** [comment]
I know it has worked in the past with other deprecated addins so I'm surprised that it didn't work in this case. Hold on, let me investigate real quick...

**Comment by Jericho** [comment]
It works: https://github.com/cake-build/website/issues/771

I wonder if there was a delay for the "deprecated" flag to be propagated on nuget.org???

**Comment by gep13** [comment]
LGTM!

**Pull request merged**
