### PR TITLE
Infrastructure for supporting more extension types

### PR DESCRIPTION
**Pull request by pascalberger**
Add infrastructure for supporting additional extension types, like modules and recipes.

This PR doesn't yet contain UI for any additional extensions, only the underlying infrastructure which allows to add them later.

Part of #131

### CODE REVIEW

**Comment by pascalberger** [comment]
Before merging addin discoverer needs to be updated to match the new folder and support the new attribute

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@pascalberger is there a corresponding issue that can be linked to for the work to Addin Discoverer?

**Comment by pascalberger** [comment]
> @pascalberger is there a corresponding issue that can be linked to for the work to Addin Discoverer?

Not yet. Will do

**Comment by pascalberger** [comment]
> @pascalberger is there a corresponding issue that can be linked to for the work to Addin Discoverer?

https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/133

**Comment by Jericho** [comment]
Discoverer is ready. Merging this PR and will release discoverer immediately.

**Pull request merged**
