### PR TITLE
Separated information for built-in functionality and addins.

### PR DESCRIPTION
**Pull request by patriksvensson**
This makes it clearer what belongs to Cake and what is third party content.

### CODE REVIEW

**Comment by gep13** [comment]
This looks good to me as well.  I can merge once the CI passes.

**Comment by patriksvensson** [comment]
@gep13 Sure. just wanted to check with you and @devlead if you're ok with this PR. In my opinion it makes it more clear what functionality is built in and removes a lot of "clutter" from the DSL pages.

**Comment by gep13** [comment]
Yip, I think this makes a lot of sense :+1:

**Comment by devlead** [comment]
Indeed :+1:

**Pull request merged**
