### PR TITLE
Added Cake.Storyteller addin

### PR DESCRIPTION
**Pull request by bibodha**

### CODE REVIEW

**Comment by bibodha** [comment]
it pulled some merges that shouldn't have been pulled in.

**Comment by gep13** [comment]
@bibodha looks like all that would have been required here is a rebase, but I see that you have opened another PR.  That's fine.  I will take a look at it later.  Thanks for doing this!

**Comment by bibodha** [comment]
Yeah. I didn't realize I had already forked and cloned this repo a while ago so I wasn't sure what happened. It all made sense later but I had already created the other PR.

**Comment by gep13** [comment]
Gotcha, not a problem at all.

**Pull request closed without merging**
