### PR TITLE
Move FAQ page to documentation section

### PR DESCRIPTION
**Pull request by pascalberger**
Move FAQ page to documentation section to get more space in main navigation for other entries, like e.g. "Community" section (https://github.com/cake-build/website/issues/928).

### CODE REVIEW

**Comment by pascalberger** [comment]
Don't know if it makes sense to keep the FAQ page with the current questions though. The answer to the pinning questions is just a link to the corresponding documentation at https://cakebuild.net/docs/writing-builds/reproducible-builds (the first sentence of the answer is no longer correct with support for the different runners and I would like to avoid duplicated docs).

The content of the last question is something I would like to add to https://cakebuild.net/docs/running-builds/.

Additionally we have search capability in the meantime which should make it easier to find the content.

**Comment by gep13** [comment]
I have no objection to moving this to within the main docs, rather than the top level navigation.

I still think that an FAQ section is a good idea.  I see it more as an index of sort.  The ability to search the docs is great, but if you aren't sure what you are looking for, having the FAQs to fall back on is a great resource.  Most likely, the FAQ would just point to the relevant piece of the documentation.

Have a look at the Chocolatey FAQ's as an example:

https://chocolatey.org/docs/chocolatey-faqs

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@pascalberger your changes have been merged, thanks for your contribution 👍

**Pull request merged**
