### PR TITLE
Improve Docs

### PR DESCRIPTION
**Pull request by kamleshjoshi55**

### CODE REVIEW

**Comment by patriksvensson** [comment]
This change isn't required, or requested, as such, I am going to close it out.

If this change is related to Hacktoberfest, then please reach out via our Gitter channel, as there are likely places where we are looking for help.

**Comment by kamleshjoshi55** [comment]
hey please don't do that.
i have just added space for Hacktoberfest.
please man!!!

**Comment by kamleshjoshi55** [comment]
he

> This change isn't required, or requested, as such, I am going to close it out.
> 
> If this change is related to Hacktoberfest, then please reach out via our Gitter channel, as there are likely places where we are looking for help.

Why???? man why?????????????

**Comment by gep13** [comment]
@kamleshjoshi55 as per the rules of Hacktoberfest...

> To earn your Hacktoberfest tee or tree reward, you must register and make four valid pull requests (PRs) between October 1-31 (in any time zone). PRs can be made to any public repo on GitHub, not only the ones with issues labeled Hacktoberfest. If a maintainer reports your pull request as spam or behavior not in line with the project’s code of conduct, you will be ineligible to participate. This year, the first 70,000 participants who successfully complete the challenge will be eligible to receive a prize.

The idea is that you make meaningful contributions to a project, not unsolicited changes that weren't requested, and serve no real purpose.  I would encourage you to read the rules of the competition, and think about your contributions before making any additional PRs to this repository, or others.

**Pull request closed without merging**
