### PR TITLE
Fix HipChat add-in repository link

### PR DESCRIPTION
**Pull request by Structed**
Fixes cake-build/website#172

### CODE REVIEW

**Comment by gep13** [comment]
@Structed are you familiar with the concept of rebasing commits? If so, can you rebase this PR into a single commit.

**Comment by Structed** [comment]
Yes, I do know the concept, but absolute github noob and we never used rebase here at our projects. However, I'd like to dig into this, but need a bit of time.

**Comment by gep13** [comment]
@Structed Perfect!

Hopefully this will help:

https://github.com/cake-build/cake/blob/develop/CONTRIBUTING.md#respond-to-feedback-on-pull-request

If not, give us a shout, and we can guide you through the process.

**Comment by gep13** [comment]
Once you have done it a couple times, it becomes second nature, and a very natural way of keeping branches up to date, without having to pull in multiple merge commits.

**Comment by Structed** [comment]
Thank you, @gep13 - very much appreciated! Will probably be able to get this done tonight.

**Comment by gep13** [comment]
@Structed nice one. Let us know if you run into any problems.

**Pull request merged**
