### PR TITLE
Cake.Issues blog post

### PR DESCRIPTION
**Pull request by pascalberger**
Add blog post about the Cake.Issues addins

### CODE REVIEW

**Comment by pascalberger** [comment]
@gep13 As discussed the blog post. Please let me know if this fits from a structure and content point of view

**Comment by gep13** [comment]
@pascalberger this looks great to me!!  Thank you very much for getting this written up!

**Comment by gep13** [comment]
@cake-build/cake-team everyone else okay with this?  Would love to get this published.

**Comment by gep13** [comment]
3 out of 5 is good enough for me 😄 

Merged here: https://github.com/cake-build/website/commit/008a6e3d577209527b62c842cf80a109cede9d18

**Comment by gep13** [comment]
@pascalberger thank you very much for writing this up!

**Pull request closed without merging**
