### PR TITLE
The big one

### PR DESCRIPTION
**Pull request by daveaglick**
atom-bomb

A couple notes:
- The build takes about 10 minutes on my machine. Most of that time is spent generating the API docs, including addins. One of the next things I'm planning to look at in Wyam is across the board performance so this will get better. It can also be reduced in testing by limiting the number of addin packages that get loaded (by temporarily deleting or moving `addin/*.yml` files).
- I did not attempt to port the deployment scripts and left them in the `old` folder. I don't know enough about Kudu deployments and figured it would be faster for one of you to just take a look. It should be easy - basically just need to upload everything in the `output` folder after generation.

### CODE REVIEW

**Comment by devlead** [comment]
@daveaglick cool 👍 I'm a bit busy right now, but I'll try to take a stab at the Kudu script ASAP in the [cake-build-bot/website](https://github.com/cake-build-bot/website) repo it publishes to [cakebuildbotdevelop.azurewebsites.net](http://cakebuildbotdevelop.azurewebsites.net/).

**Comment by devlead** [comment]
Haven't investigated yet but just running build.ps1 resulted in
```
========================================
Build
========================================
Executing task: Build
An error occurred when executing task 'Build'.
Error: Object reference not set to an instance of an object.
```

**Comment by daveaglick** [comment]
@devlead Why you gotta be harshing my vibe like that, man?!

(pushed a fix and replaced the branch - should work now, just forgot to copy over a quick last-minute fix in the build script to all the build targets)

**Comment by daveaglick** [comment]
Should also be noted I've updated http://cakedocs.azurewebsites.net/ with the output of this PR

**Comment by devlead** [comment]
@daveaglick cool will try later.

Btw. this hack made addin restore allot faster on my machine went from 200-500kbs network usage to 8-60mbs  
```cake
Task("GetAddinPackages")
    .IsDependentOn("CleanAddinPackages")
    .IsDependentOn("GetAddinSpecs")
    .Does(() =>
    {
        DirectoryPath   packagesPath        = MakeAbsolute(Directory("./output")).Combine("packages");
        System.Threading.Tasks.Parallel.ForEach(
            addinSpecs.Where(x => !string.IsNullOrEmpty(x.NuGet)).ToArray(),
            addinSpec => {
                Verbose("Installing addin package " + addinSpec.NuGet);

                var addInVersionUrl = string.Format("https://www.nuget.org/api/v2/Packages()?$filter=Id%20eq%20'{0}'%20and%20IsAbsoluteLatestVersion%20eq%20true",
                                    Uri.EscapeDataString(addinSpec.NuGet));
                string addinVersion;
                try
                {
                    addinVersion = (
                        from feed in System.Xml.Linq.XDocument.Load(addInVersionUrl).Elements()
                        from entry in feed.Elements().Where(element => element.Name.LocalName == "entry")
                        from properties in entry.Elements().Where(element => element.Name.LocalName == "properties")
                        from version in properties.Elements().Where(element => element.Name.LocalName == "Version")
                        select version.Value
                    ).FirstOrDefault();
                }
                catch(Exception ex)
                {
                    addinVersion = null;
                    Information("Failed to fetch version for addin {0} ({1})...", addinSpec.NuGet, ex.Message);
                }

                NuGetInstall(addinSpec.NuGet,
                    new NuGetInstallSettings
                    {
                        OutputDirectory = addinDir,
                        Prerelease = addinSpec.Prerelease,
                        Version = addinVersion,
                        Source = new [] { "https://api.nuget.org/v3/index.json" },
                        NoCache = true,
                        EnvironmentVariables    = new Dictionary<string, string>{
                            {"EnableNuGetPackageRestore", "true"},
                            {"NUGET_XMLDOC_MODE", "None"},
                            {"NUGET_PACKAGES", packagesPath.FullPath},
                            {"NUGET_EXE",  Context.Tools.Resolve("nuget.exe").FullPath }
                    }});
            });
    });
```

It's not perfect(packagesPath would obviously be global var) ... but something along those lines would be benefical. Also the above environmen variables sorts a few nuget issues espicially on Azure.

**Comment by patriksvensson** [comment]
@daveaglick Looks good to me! I noticed that enum values are not showing, is this difficult to fix? http://cakedocs.azurewebsites.net/api/Cake.Common.Tools.MSBuild/PlatformTarget

Also, if we wanted to apply the old look and feel to the new site, would it be a lot of work? Not saying that you should do it, just wanted to know if it is possible 😄

**Comment by patriksvensson** [comment]
@daveaglick The `Wyam` link in your blog post is not rendered correctly. I think you have an extra `(` in the link: http://cakedocs.azurewebsites.net/blog/2016/12/new-static-site

**Comment by devlead** [comment]
@daveaglick @cake-build/team got a deployment scrip that works here https://github.com/cake-build-bot/website/commit/2be1012620644ddfe5db67a69a6e2bc589509011
image

It deployed to http://cakebuildbotdevelop.azurewebsites.net/

So that's good...but it takes a while though, so there might be some room for optimization
image
The summary
```
Task                          Duration            
--------------------------------------------------
CleanSource                   00:00:32.4351718    
GetSource                     00:00:18.4474457    
CleanAddinPackages            00:00:12.7746391    
GetAddinSpecs                 00:00:00.5017157    
GetAddinPackages              00:03:54.8570176    
Build                         00:26:14.1327642    
Deploy                        00:04:21.8032331    
--------------------------------------------------
Total:                        00:35:34.9526734    
```

As initial Deploy takes 4 minutes I'm wondering if the issue is IO bound. Second deployment looked like this
```
Task                          Duration            
--------------------------------------------------
CleanSource                   00:00:39.2481583    
GetSource                     00:00:20.2663395    
CleanAddinPackages            00:00:18.7782270    
GetAddinSpecs                 00:00:00.5651462    
GetAddinPackages              00:04:53.8957115    
Build                         00:28:02.7549625    
Deploy                        00:02:26.8457599    
--------------------------------------------------
Total:                        00:36:42.3549815  
```

So actual copying files a fair bit faster the second time, looking at the details of the pipelines `RenderApi` takes about 17 minutes out of 24 to render
```
2016-12-21T08:15:41.5725554Z    Executing 22 pipelines
2016-12-21T08:15:41.5881730Z        Executing pipeline "Addins" (1/22) with 2 child module(s)
2016-12-21T08:15:42.4515943Z            Executed pipeline "Addins" (1/22) in 884 ms resulting in 74 output document(s)
2016-12-21T08:15:42.4687368Z        Executing pipeline "AddinCategories" (2/22) with 4 child module(s)
2016-12-21T08:15:42.5297300Z            Executed pipeline "AddinCategories" (2/22) in 68 ms resulting in 47 output document(s)
2016-12-21T08:15:42.5297300Z        Executing pipeline "Code" (3/22) with 1 child module(s)
2016-12-21T08:15:48.7766786Z            Executed pipeline "Code" (3/22) in 6249 ms resulting in 733 output document(s)
2016-12-21T08:15:48.7921240Z        Executing pipeline "Api" (4/22) with 1 child module(s)
2016-12-21T08:16:09.8368340Z            Executed pipeline "Api" (4/22) in 21059 ms resulting in 7132 output document(s)
2016-12-21T08:16:09.8531534Z        Executing pipeline "DslAliases" (5/22) with 4 child module(s)
2016-12-21T08:16:09.9305870Z            Executed pipeline "DslAliases" (5/22) in 90 ms resulting in 108 output document(s)
2016-12-21T08:16:09.9466249Z        Executing pipeline "Pages" (6/22) with 11 child module(s)
2016-12-21T08:17:40.5853853Z            Executed pipeline "Pages" (6/22) in 90655 ms resulting in 4 output document(s)
2016-12-21T08:17:40.6478826Z        Executing pipeline "BlogPosts" (7/22) with 12 child module(s)
2016-12-21T08:18:11.9471900Z            Executed pipeline "BlogPosts" (7/22) in 31359 ms resulting in 42 output document(s)
2016-12-21T08:18:11.9766093Z        Executing pipeline "BlogIndexes" (8/22) with 1 child module(s)
2016-12-21T08:18:19.0247855Z            Executed pipeline "BlogIndexes" (8/22) in 7078 ms resulting in 9 output document(s)
2016-12-21T08:18:19.0404884Z        Executing pipeline "BlogCategories" (9/22) with 1 child module(s)
2016-12-21T08:18:34.3848328Z            Executed pipeline "BlogCategories" (9/22) in 15353 ms resulting in 12 output document(s)
2016-12-21T08:18:34.3848328Z        Executing pipeline "BlogArchives" (10/22) with 1 child module(s)
2016-12-21T08:19:27.0017955Z            Executed pipeline "BlogArchives" (10/22) in 52380 ms resulting in 27 output document(s)
2016-12-21T08:19:27.0185573Z        Executing pipeline "BlogAuthors" (11/22) with 1 child module(s)
2016-12-21T08:19:45.9308458Z            Executed pipeline "BlogAuthors" (11/22) in 19151 ms resulting in 13 output document(s)
2016-12-21T08:19:45.9464713Z        Executing pipeline "BlogFeed" (12/22) with 1 child module(s)
2016-12-21T08:19:46.7762530Z            Executed pipeline "BlogFeed" (12/22) in 839 ms resulting in 2 output document(s)
2016-12-21T08:19:46.7762530Z        Executing pipeline "RenderPages" (13/22) with 1 child module(s)
2016-12-21T08:19:57.1477275Z            Executed pipeline "RenderPages" (13/22) in 10372 ms resulting in 45 output document(s)
2016-12-21T08:19:57.1633528Z        Executing pipeline "RenderBlogPosts" (14/22) with 1 child module(s)
2016-12-21T08:20:09.3620214Z            Executed pipeline "RenderBlogPosts" (14/22) in 12218 ms resulting in 42 output document(s)
2016-12-21T08:20:09.3776462Z        Executing pipeline "Redirects" (15/22) with 4 child module(s)
2016-12-21T08:20:09.4401484Z            Executed pipeline "Redirects" (15/22) in 77 ms resulting in 0 output document(s)
2016-12-21T08:20:09.4715797Z        Executing pipeline "RenderApi" (16/22) with 1 child module(s)
2016-12-21T08:37:42.2793441Z            Executed pipeline "RenderApi" (16/22) in 1052777 ms resulting in 7132 output document(s)
2016-12-21T08:37:42.2793441Z        Executing pipeline "ApiIndex" (17/22) with 1 child module(s)
2016-12-21T08:37:59.4047438Z            Executed pipeline "ApiIndex" (17/22) in 17152 ms resulting in 1 output document(s)
2016-12-21T08:37:59.4207208Z        Executing pipeline "ApiSearchIndex" (18/22) with 1 child module(s)
2016-12-21T08:38:00.2655905Z            Executed pipeline "ApiSearchIndex" (18/22) in 852 ms resulting in 1 output document(s)
2016-12-21T08:38:00.2655905Z        Executing pipeline "Less" (19/22) with 6 child module(s)
2016-12-21T08:38:16.2717451Z                Warning: extend '.clearfix' has no matches on line 11 in file '../bootstrap/mixins/grid.less':
2016-12-21T08:38:16.2900972Z     [10]:   padding-right: ceil((@gutter / 2));
2016-12-21T08:38:16.3029956Z     [11]:   &:extend(.clearfix all);
2016-12-21T08:38:16.3186918Z           --^
2016-12-21T08:38:16.3186918Z     [12]: }
2016-12-21T08:38:16.3344355Z    
2016-12-21T08:38:16.3498720Z                Warning: extend '.close' has no matches on line 87 in file 'mailbox.less':
2016-12-21T08:38:16.3677618Z     [86]: .mailbox-attachment-close {
2016-12-21T08:38:16.3811239Z     [87]:   &:extend(.close);
2016-12-21T08:38:16.3967830Z           --^
2016-12-21T08:38:16.4123887Z     [88]: }
2016-12-21T08:38:16.4123887Z    
2016-12-21T08:38:16.8655035Z            Executed pipeline "Less" (19/22) in 16604 ms resulting in 4 output document(s)
2016-12-21T08:38:16.8845456Z        Executing pipeline "Resources" (20/22) with 1 child module(s)
2016-12-21T08:38:18.7017481Z            Executed pipeline "Resources" (20/22) in 1831 ms resulting in 48 output document(s)
2016-12-21T08:38:18.7173684Z        Executing pipeline "RenderAddins" (21/22) with 3 child module(s)
2016-12-21T08:38:35.7752155Z            Executed pipeline "RenderAddins" (21/22) in 17072 ms resulting in 47 output document(s)
2016-12-21T08:38:35.7908417Z        Executing pipeline "RenderDsl" (22/22) with 5 child module(s)
2016-12-21T08:39:11.2584680Z            Executed pipeline "RenderDsl" (22/22) in 35480 ms resulting in 108 output document(s)
2016-12-21T08:39:13.7347879Z        Executed 22/22 pipelines in 1412166 ms
```

Wyam uses a bit of memory, maybe it should use more :) have 3,5GB on this Azure app service
image

**Comment by gep13** [comment]
When browsing on my phone, I see a solid black dot which is the go to top button, is anyone else seeing that?

wp_ss_20161221_0001

**Comment by gep13** [comment]
Actually, looks like this is only an issue on the cakebot version. When I browse the site that @daveaglick created, I correctly see the up arrow.

**Comment by devlead** [comment]
@gep13 could be file missing, or web.config needed (if I.e. non standard content type)

@daveaglick temporarily set web to Standard 3 (twice the cores&ram) and it was almost twice as fast, still takes a while.
```
Task                          Duration            
--------------------------------------------------
CleanSource                   00:00:21.4228420    
GetSource                     00:00:14.9053313    
CleanAddinPackages            00:00:12.9623966    
GetAddinSpecs                 00:00:00.3854928    
GetAddinPackages              00:00:58.1838260    
Build                         00:13:53.8128732    
Deploy                        00:01:26.4707440    
--------------------------------------------------
Total:                        00:17:08.1436009    
```

**Comment by daveaglick** [comment]
> I noticed that enum values are not showing, is this difficult to fix? 

That looks like a bug - shouldn't be hard to fix. It'll need a new release, so I'll try to get one out in the next couple days (maybe today if I'm lucky). I've opened Wyamio/Wyam#363 to track.

> Also, if we wanted to apply the old look and feel to the new site, would it be a lot of work?

Definitely possible. The data and generation pipelines are (mostly) totally separated from the presentation. The docs recipe is complicated enough that I only plan on shipping one stock theme, but overriding it in certain ways isn't hard. The main layout is in a single file, so replacing that and keeping the rest of the theme would get us 80% - 90% there. Then we'd need to tweak some other theme files that make assumptions about the CSS, but it's certainly possible to restyle.

> The Wyam link in your blog post is not rendered correctly

Will update the PR momentarily. Happy for some proofreading or any suggestions for the blog post.

> it takes a while though, so there might be some room for optimization

This is the achilles heel of Wyam right now. Now that the docs recipe is done, my next big push is going to be performance and memory use. The two areas that need the most attention are walking the dependency tree with NuGet when Wyam brings down required packages and the memory/performance of code analysis activities.

The latter is a tough one and I'm going to need to play with some tradeoffs. Right now, Wyam keeps the entire Roslyn semantic tree resident in memory. This is important so we can lazily access symbols that aren't "inside" the initial compilation. For example, that's why we can build those pretty hierarchy graphs and include base symbols from the core libraries. If we were to eagerly process the Roslyn semantic model, we would have to choose to either omit core symbols or include all of them (essentially the entire core framework). Neither is a great option.

I do have some ideas on how to make it faster and use less memory, but it won't be a quick and dirty fix (or maybe it will be! just don't know yet).

> takes about 17 minutes out of 24 to render

Yeah, a 30 minute render job is rough. In a CI process, I don't see that as being a huge deal (as long as the VM doing the build doesn't time out), but it'll be painful for local testing. I can write up a page on how to efficiently build and test locally. Basically it just boils down to temporarily deleting the addin YAML files. Pulling in so many assemblies, creating a semantic model for them all using reflection, and then generating almost 8,000 API pages is what's eating that time.

> Actually, looks like this is only an issue on the cakebot version.

Strange! The arrow is from Font Awesome which is being delivered by bootstrapcdn.com right now (I've been considering packaging everything locally instead of using common CDNS - there's pros and cons to that). Maybe the CDN just crapped out momentarily. I see the arrow on both deployment endpoints from my iPhone.

> temporarily set web to Standard 3 (twice the cores&ram) and it was almost twice as fast,

Suspect some of the time may be Roslyn causing disk swapping under memory pressure. I personally wouldn't worry too much about CI build times unless it needs to be part of a more rapid release cycle. And this will hopefully continue to get better as I dig in more deeply.

**Comment by devlead** [comment]
Normally build times above 10 minutes would cause issues, but I raised timeout to an hour so it should at least not timeout now

**Comment by daveaglick** [comment]
I fixed the issue with fields (enums) and will publish a new release shortly.

I'm currently looking through a profile to see if there are any easy wins on performance. It looks like the bulk of the time is being used by Razor compiling and rendering each of those ~8,000 Razor pages. I was a version behind on ASP.NET Core, so I'm currently attempting to bump all the packages and see if that shows any improvement (I know they've been working on the pre-compilation story for Razor, which is very similar to what Wyam does).

**Comment by daveaglick** [comment]
So I did successfully bump Razor and Roslyn versions and there was indeed a corresponding performance boost (at least anecdotally). Unfortunately, upgrading those two frameworks caused all sorts of dependency resolution problems (particularly with the NuGet APIs) and runtime binding exceptions. It's not intractable, but will take some time to work through.

I'll publish a release with the enum fix for now so we can move forward. I'll continue to work on performance as originally planned and that should gradually get better, but unless you think it's a blocker for now I would suggest proceeding.

**Comment by daveaglick** [comment]
I came up with a clever caching strategy for the Razor rendering on my drive home last night that anecdotally appears to reduce pipeline times for certain pipelines like RenderApi by as much as 2/3! Memory pressure appears reduced too. I'll publish another release shortly - want to try a couple additional things.

At this point, are you waiting on anything else from me? It's totally fine if more review time is needed - just want to make sure it's not being held up from my end.

**Comment by daveaglick** [comment]
Okay, just published the new version. That's it for the easy performance and memory wins. Additional gains will take some time to realize.

**Comment by devlead** [comment]
@daveaglick first try gave an exception, will clean repo and try again
```
Executing 22 pipelines
    Executing pipeline "Addins" (1/22) with 2 child module(s)
        Executed pipeline "Addins" (1/22) in 247 ms resulting in 74 output document(s)
    Executing pipeline "AddinCategories" (2/22) with 4 child module(s)
        Executed pipeline "AddinCategories" (2/22) in 37 ms resulting in 47 output document(s)
    Executing pipeline "Code" (3/22) with 1 child module(s)
        Executed pipeline "Code" (3/22) in 459 ms resulting in 733 output document(s)
    Executing pipeline "Api" (4/22) with 1 child module(s)
                    Error while executing module AnalyzeCSharp
                Error while executing module Execute
            Error while executing module If
        Error while executing pipeline Api
Exception during execution: System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Immutab
le, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot fin
d the file specified.
File name: 'System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Wyam.CodeAnalysis.AnalyzeCSharp.Execute(IReadOnlyList`1 inputs, IExecutionContext context)
   at Wyam.Core.Execution.Pipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 documents)
in E:\Code\Wyam\src\core\Wyam.Core\Execution\Pipeline.cs:line 252
   at Wyam.Core.Execution.ExecutionContext.Execute(IEnumerable`1 modules, IEnumerable`1 inputs, IEnumerable`1 items) in
E:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionContext.cs:line 212
   at Wyam.Core.Execution.ExecutionContext.Execute(IEnumerable`1 modules, IEnumerable`1 inputs) in E:\Code\Wyam\src\core
\Wyam.Core\Execution\ExecutionContext.cs:line 190
   at Wyam.Core.Modules.Extensibility.Execute.ExecuteModules(Object results, IExecutionContext context, IEnumerable`1 in
puts) in E:\Code\Wyam\src\core\Wyam.Core\Modules\Extensibility\Execute.cs:line 149
   at Wyam.Core.Modules.Extensibility.Execute.Wyam.Common.Modules.IModule.Execute(IReadOnlyList`1 inputs, IExecutionCont
ext context) in E:\Code\Wyam\src\core\Wyam.Core\Modules\Extensibility\Execute.cs:line 116
   at Wyam.Core.Execution.Pipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 documents)
in E:\Code\Wyam\src\core\Wyam.Core\Execution\Pipeline.cs:line 252
   at Wyam.Core.Execution.ExecutionContext.Execute(IEnumerable`1 modules, IEnumerable`1 inputs, IEnumerable`1 items) in
E:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionContext.cs:line 212
   at Wyam.Core.Execution.ExecutionContext.Execute(IEnumerable`1 modules, IEnumerable`1 inputs) in E:\Code\Wyam\src\core
\Wyam.Core\Execution\ExecutionContext.cs:line 190
   at Wyam.Core.Modules.Control.If.Execute(IReadOnlyList`1 inputs, IExecutionContext context) in E:\Code\Wyam\src\core\W
yam.Core\Modules\Control\If.cs:line 98
   at Wyam.Core.Execution.Pipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 documents)
in E:\Code\Wyam\src\core\Wyam.Core\Execution\Pipeline.cs:line 252
   at Wyam.Core.Execution.Pipeline.Execute(Engine engine) in E:\Code\Wyam\src\core\Wyam.Core\Execution\Pipeline.cs:line
146
   at Wyam.Core.Execution.Engine.Execute() in E:\Code\Wyam\src\core\Wyam.Core\Execution\Engine.cs:line 162
```

**Comment by devlead** [comment]
@daveaglick clean repo sorted it.

**Comment by daveaglick** [comment]
:thumbsup:

Curious how the new release impacts performance of your CI build. I saw the RenderApi pipeline go from 4 minutes to about 1 minute for the Wyam site build on AppVeyor.

**Comment by devlead** [comment]
First test looks faster
```
Task                          Duration            
--------------------------------------------------
CleanSource                   00:00:38.2382621    
GetSource                     00:00:18.2889676    
CleanAddinPackages            00:00:16.6891899    
GetAddinSpecs                 00:00:00.6650640    
GetAddinPackages              00:03:35.3817401    
GetArtifacts                  00:00:00.0001028    
Build                         00:16:48.6937404    
Deploy                        00:03:13.1860812    
--------------------------------------------------
Total:                        00:24:51.1431481  
```
Triggered a redeploy to see it wasn't a fluke 
```
Task                          Duration            
--------------------------------------------------
CleanSource                   00:00:37.6878686    
GetSource                     00:00:18.5076376    
CleanAddinPackages            00:00:20.6151252    
GetAddinSpecs                 00:00:00.6292066    
GetAddinPackages              00:04:46.2669246    
GetArtifacts                  00:00:00.0001055    
Build                         00:17:03.6862074    
Deploy                        00:02:23.6586510    
--------------------------------------------------
Total:                        00:25:31.0517265  
```
Third time's a charm :)
```
Task                          Duration            
--------------------------------------------------
CleanSource                   00:00:39.3290011    
GetSource                     00:00:17.7060459    
CleanAddinPackages            00:00:22.0373690    
GetAddinSpecs                 00:00:00.6120521    
GetAddinPackages              00:04:18.1173232    
GetArtifacts                  00:00:00.0000992    
Build                         00:16:23.1771536    
Deploy                        00:02:15.1959186    
--------------------------------------------------
Total:                        00:24:16.1749627    
```
So 10:isch minutes faster ain't bad at all 👍

**Comment by devlead** [comment]
@daveaglick how are the redirects done
I.e. [api/cake.core/f005e67e](http://cakebuild.net/api/cake.core/f005e67e) should go to [api/Cake.Core/ICakeContext](http://cakebuildbotdevelop.azurewebsites.net/api/Cake.Core/ICakeContext) but seems to 404 now. 
Also see we've changed casing could that be an issue?

**Comment by daveaglick** [comment]
Redirects from the content or blog pages are easy - there's a front matter setting we can use for those (though in this case, we don't actually need any redirects since the URLs are all the same).

For the API we had talked about trying to match up the hash code generation, but I could never get it quite right (Roslyn exposes slightly different information than reflection in some cases). We can either manually generate a set of placeholder HTML files with meta refresh redirects and just copy them over on each build. Or we can not worry about the API links since they were recently changed anyway and guide people towards the API search on the 404 page. I did make sure all the existing API links on content and blog posts point to the new API URLs.

**Comment by daveaglick** [comment]
I've pushed all the changes since porting everything. Since this PR essentially blows up all the old stuff, I didn't want to rebase and risk messing something up so it'll probably have to be merged manually and pushed with a history rewrite.

**Comment by daveaglick** [comment]
A local rebase actually appears to have worked okay (git is magic). Once I verify the build locally, I'll push the rebased version so you won't have to rewrite history.

**Comment by daveaglick** [comment]
Okay, all that's left now is for @devlead to do some of his devops wizardry

**Comment by patriksvensson** [comment]
Old site, rest in pieces 💀 🔫

**Pull request merged**
