### PR TITLE
Enabled parallel addin installation

### PR DESCRIPTION
**Pull request by devlead**
Attempt to speed up build process by doing addin installation in parallel, locally it made quite the difference, but might have side effects.

```diff
- GetAddinPackages              00:08:33.5422183
+ GetAddinPackages              00:01:42.6093914
```

### CODE REVIEW

**Comment by devlead** [comment]
Preliminary diff on AppVeyor

```diff
- GetAddinPackages              00:04:42.7043475 
+ GetAddinPackages              00:01:53.4593429  
```

**Comment by patriksvensson** [comment]
Awesome!

**Comment by daveaglick** [comment]
Nice!

**Comment by devlead** [comment]
@cake-build/cake-team I've merged, lets keep an eye out for anything weird that might happen ;)

**Pull request merged**
