### PR TITLE
Add targeted Cake version in YAML files

### LINKED ISSUE #1270: Add targeted Cake version in YAML files
Adding the `TargetCakeVersion` property.

### PR DESCRIPTION
**Pull request by Jericho**
This pull request was created by a tool: Cake.AddinDiscoverer version 3.54.1

Resolves #1270

### CODE REVIEW

**Review by pascalberger — APPROVED** [review]
LGTM

**Comment by Jericho** [comment]
This is the first batch of 75. As soon as this PR is merged, I will submit the next batch of 75 and so on until all 300+ YAML file are modified.

**Comment by pascalberger** [comment]
Seems like parser is not happy with the unknown field. I'll have a look and update the parser

**Comment by Jericho** [comment]
ok

**Comment by pascalberger** [comment]
@Jericho your changes have been merged, thanks for your contribution 👍

**Pull request merged**
