### PR TITLE
Remove Cake.DotNetTool.Module as it ships now with Cake

### PR DESCRIPTION
**Pull request by pascalberger**
Remove Cake.DotNetTool.Module as it ships now with Cake since 1.1 (see https://github.com/cake-build/cake/issues/2903). 

Related PR to exclude in addin discoverer: https://github.com/cake-contrib/Cake.AddinDiscoverer/pull/184

### CODE REVIEW

**Comment by augustoproiete** [comment]
LGTM.

However, I'm wondering :thinking: if it wouldn't be better to leave this module in the website for the time being, and add an alert on its page with the same text that we have on the blog post, e.g.:

image

It could be hard-coded in the page for now (e.g. `if (extensionName == "Cake.DotNetTool.Module") ...` just to have something quick, given that we don't yet have a feature to add custom notes about a specific extension.

**Comment by pascalberger** [comment]
Thought about this as well. It was only added recently and there and we generally only document current version on website and not previous versions (e.g. removed command line switches). 

On the other hand it is not a big deal to add a not as you suggested and would be OK for me. To be consistent we should in this case document the latest version of the extension which was not bundled (1.0.1).

@Jericho If we keep the YAML file of the old version here, would it work with excluding it in Addin Discoverer? Or will it then try to remove it?

**Comment by Jericho** [comment]
> @Jericho If we keep the YAML file of the old version here, would it work with excluding it in Addin Discoverer? Or will it then try to remove it?

Excluding this module means that discoverer will neither update nor delete this yaml which, if I understand correctly, is exactly what you want.

**Comment by Jericho** [comment]
Discoverer 3.70.0 published. The module is now excluded from analysis.

**Comment by augustoproiete** [comment]
Closing this one now that `Cake.DotNetTool.Module` has been blacklisted in AddinDisco. We'll document it via https://github.com/cake-build/website/issues/1739

**Pull request closed without merging**
