### PR TITLE
Add comparison page for different runners

### PR DESCRIPTION
**Pull request by pascalberger**
Add a page for comparison between the different available runners.

### CODE REVIEW

**Comment by pascalberger** [comment]
Wait until #1003 is merged

**Comment by pascalberger** [comment]
Would also like to add a column for debug support once #83 is done

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@pascalberger if you can get this rebased, I will get it merged.

**Comment by pascalberger** [comment]
> @pascalberger if you can get this rebased, I will get it merged.

Let me first update it to reference IntelliSense documentation. Also debug column needs to be removed as long as #83 is not implemented.

**Comment by pascalberger** [comment]
@gep13 This is now ready for review. I made some more changes and integrated the table into the existing page.

**Review by gep13 — APPROVED** [review]
LGTM!

**Pull request merged**
