### PR TITLE
Simple blog-post on the release of Cake for Rider

### PR DESCRIPTION
**Pull request by nils-a**
version 1.0.0

### CODE REVIEW

**Review by ecampidoglio — APPROVED** [review]
LGTM.

**Comment by nils-a** [comment]
Cake for Rider 1.0.0 has been released 🎉 
I will merge this PR, once it has been approved by JetBrains

**Review by gep13 — APPROVED** [review]
LGTM!

**Review by augustoproiete — APPROVED** [review]
LGTM

**Pull request merged**
