### PR TITLE
Extending Bootstrapper Documentation

### PR DESCRIPTION
**Pull request by RLittlesII**
This doesn't include the bash.  I just wanted to be sure this was useful before I went any further. I'll rebase before any merge.

### CODE REVIEW

**Comment by gep13** [comment]
@RLittlesII I think that this makes sense to me, yes.  In the heading section, would it be possible to call out what you are doing?  i.e. give it a scenario.

`The Cake Bootstrapper that you can get directly from cakebuild.net is intended as a sample on what can be done.  It is entirely possible that you can extend the bootstrapper to include your own requirements.  For example, let's say you want to add you own input parameter to the bootstrapper called buildConfiguration.  These are the changes that you would need to make in order to achieve this...`

What do you think?

**Comment by RLittlesII** [comment]
I like it.  I have another scenario to add, so that definitely makes sense.  I'll update with the rest of the documentation and scenarios. Is it necessary to add a bash example?

**Comment by gep13** [comment]
@RLittlesII for the sake of completeness, I would say that yes, we should have the same examples in bash, as well as PowerShell.

**Comment by RLittlesII** [comment]
@gep13 I'll make sure to prefix it to show PowerShell vs Bash.

**Comment by RLittlesII** [comment]
@gep13 I still have to test that the documentation works on bash.  Comments on making sure the look and feel of the document vibe with the rest of the cake site is appreciated.  I don't want this to read like it came from me.  :smile:

**Comment by gep13** [comment]
@RLittlesII this looks really good to me so far!  The only comment would be to perhaps make the changes that you have made in the code snippets bold, so that they can stand out.  What do you think?

**Comment by RLittlesII** [comment]
@gep13 I think calling out the specific change would ultimately make it more useful.  I am not aware of how to bold something inside of a code block in mark down.  Maybe I add a comment on the end of the line that says `// This line was added` or something to that affect?  If you know how, let me know.

**Comment by gep13** [comment]
```
**bold**
not bold
```

**Comment by gep13** [comment]
@RLittlesII hmm, I thought there was a direct way, but looks like there isn't :-(

In the above, I did what was suggested here:

http://meta.stackexchange.com/questions/183610/how-to-combine-bold-and-code-sample-in-markdown

**Comment by gep13** [comment]
But anyway, I agree, calling out the specific thing that has changed, would ultimately make the most sense.

**Comment by RLittlesII** [comment]
@gep13 I found the same post and was equally disappointed that it did not work.  I will add comments to the code sample.

**Comment by RLittlesII** [comment]
@gep13 Are the changes sufficient?  I have tried to bold the line, but it doesn't seem to work correctly.

**Comment by gep13** [comment]
@RLittlesII this all looks good to me, with only one suggestion...

Can you add an example of the command that you would use to run the bootstrapper in each case?  This would be especially helpful in the second example, to show passing in two build configurations.

Thanks!

**Comment by RLittlesII** [comment]
@gep13 I just realized that passing array's at the bash shell is clunky.  I need to prove it works before I add it.

**Comment by gep13** [comment]
@RLittlesII not a problem at all.  Let me know when you are ready for me to take a look again.

**Comment by RLittlesII** [comment]
@gep13 I am inclined to remove the part about array's that way we can close this out and I can add it once I've done the research.

**Comment by gep13** [comment]
@RLittlesII that sounds fine with me.  You want to fix it up and I can get it merged in?

**Comment by RLittlesII** [comment]
Fixed up and rebased.

**Comment by gep13** [comment]
@RLittlesII perfect, thank you!

**Pull request merged**
