### PR TITLE
Adding blog post for VSWhere.

### PR DESCRIPTION
**Pull request by phillipsj**
#322 Just got this most of the way and thought you all would want to review.

### CODE REVIEW

**Comment by devlead** [comment]
@phillipsj what you've done so far looks good to me, ping us when you pushed any changes for review.

**Comment by phillipsj** [comment]
Ok, I removed the comment and once I get the information I can do another post or update this one.

**Comment by phillipsj** [comment]
@devlead @gep13  This is ready to go on my side, I got the last piece that I really wanted with the list of components.

**Comment by devlead** [comment]
@phillipsj  your changes have been merged, thanks for your contribution 👍

**Pull request merged**
