### PR TITLE
Exclude Cake.Frosting.Example & Cake.Frosting.Template from API

### LINKED ISSUE #1548: Hide Cake.Frosting.Example from API documentation
Cake.Frosting.Example project should be excluded from API documentation (e.g. https://cakebuild.net/api/global/HelloTask/)

### PR DESCRIPTION
**Pull request by mgnslndh**
This PR excludes two projects from the Cake repo from being part of the API documentation. 

Fixes #1548

### CODE REVIEW

**Review by pascalberger — APPROVED** [review]
LGTM

**Comment by pascalberger** [comment]
@mgnslndh your changes have been merged, thanks for your contribution 👍

**Comment by mgnslndh** [comment]
Hi @pascalberger! Hacktoberfest has not yet accepted this PR even though it has been merged. If possible, could you please add the "hacktoberfest-accepted" label to this PR and hopefully that works better?

**Comment by pascalberger** [comment]
@mgnslndh Sure, I added the label

**Comment by mgnslndh** [comment]
Thanks @pascalberger I appreciate you taking the time!

**Pull request merged**
