### PR TITLE
Add Cake.Android.AvdManager

### PR DESCRIPTION
**Pull request by Redth**

### CODE REVIEW

**Comment by Redth** [comment]
NM, it's there.

**Comment by gep13** [comment]
@Redth there is an automated service running which @Jericho created which handles updating the addins that are out there, so manually updating these files isn't required anymore 😄

**Comment by Jericho** [comment]
@gep13 I vaguely remember that there's documentation somewhere (I don't remember where) which was written before we implemented the automated process that instructs addin authors to manually create YAML files. We need to update this recommendation to let authors know that the automated process uses the package nuspec to generate the content of the YAML file and therefore it's important to keep the nuspec up to date.

**Comment by Redth** [comment]
Yeah my super ancient neglected repo's had advice in some of them to come add a yml file here 😂

**Comment by gep13** [comment]
@Redth @Jericho if we can track down that documentation, then yes, we should definitely update it 😄

**Comment by Jericho** [comment]
@Redth Thanks for taking care of recommendations in all your repos. One quick note: in most cases, the issues and PRs you are closing were more than a year old and some recommendations have changed in the intervening time. One such recommendation that come to mind is the icon URL. The old recommendation was to use a URL that dependeded on `cdn.rawgit.com` but this CDN will be going out of business in a few months. Therefore the new recommendation is to use the following: `https://cdn.jsdelivr.net/gh/cake-contrib/graphics/png/cake-contrib-medium.png`.

**Comment by Jericho** [comment]
- The automated process used to recommend manually creating YAML files but it no longer does since summer 2018 (https://github.com/cake-contrib/Cake.AddinDiscoverer/commit/1e2caab8dbb70b7e6da0a0b293b21a15a352c49a).

- There is a quick mention of submitting a PR to add your addin to Cake's web site [here](https://github.com/cake-contrib/Home/blob/89363994fd1801aa4cd546418d9d82aa0ba3e327/README.md#tracking-addins-modules-and-recipes). I will submit a PR to update the paragraph.

- I also found that the paragraph in the guideline that recommended manually creating YAML files was [removed in June 2018](https://github.com/cake-contrib/Home/commit/9b6852441b3d935487c6e5cd91636ad6acdbf2f2#diff-d27dac9e32b0ee78e0940838ae318c08).

**Comment by gep13** [comment]
@Jericho cool, sounds like most places are covered.  Thanks for investigating!

**Comment by Redth** [comment]
Awesome, I went and updated the icon url image again anywhere that had the old URL.

@Jericho will this automation run regularly on these repositories?

**Comment by Jericho** [comment]
@Redth The automated process runs twice a day (at noon and midnight UTC) but keep in mind that most of the metadata that it relies on is in your addin's nuget package which means that merely changing a file in github is not enough, you must publish a new package. Hope this makes sense.

**Pull request closed without merging**
