### PR TITLE
adds Cake.Npm and Cake.Gulp addins

### PR DESCRIPTION
**Pull request by Philo**

### CODE REVIEW

**Comment by devlead** [comment]
@Philo Hi, namespaces need to be documented you can see an example of that here:
https://github.com/WCOMAB/Cake.Slack/blob/master/src/Cake.Slack/Properties/Namespaces.cs

**Comment by Philo** [comment]
@devlead - I've added the class as above to both Cake.Npm and Cake.Gulp

**Comment by devlead** [comment]
Ok great, will review and merge if ok later.

One tip saw that you currently check for gulp.cmd & node.exe, to be xplat you should also check for `node`, `nodejs` and `gulp` in your `GetToolExecutableNames()`

**Comment by devlead** [comment]
@Philo tip 2 also your nugets don't need a dependency on Cake.Core as it's already in place when add-ins are loaded, saves a little time when add-ins are installed (otherwise Cake.Core is downloaded and installed in the add in folder but never used).

**Comment by devlead** [comment]
@Philo this is now merged and available on the website, thanks for your contribution :+1:

**Comment by Philo** [comment]
@devlead, thanks for the feedback, will update accordingly.  I was hoping someone  wouldpoint me towards to xplat locations for node and nom so  Ican include xplat support

**Pull request merged**
