### PR TITLE
React to Wyam 0.16 (global metadata to settings, logo file)

### PR DESCRIPTION
**Pull request by daveaglick**
It looks like there may have been some commits directly to the master branch, so this may have to be rebased prior to merge or those may need to be brought back into the develop branch.

### CODE REVIEW

**Comment by devlead** [comment]
@daveaglick changes are in develop. 
Is this a coming breaking change?

**Comment by daveaglick** [comment]
Shouldn't be - as long as the build starts on a fresh VM and the Cake tools/addins aren't cached.

**Comment by devlead** [comment]
Cool,  LETS see 😎

**Comment by daveaglick** [comment]
This will also resolve a couple other issues like #270 and #215

**Comment by daveaglick** [comment]
Did the build fail? I'm not seeing either of the fixes for those issues in the live site...

**Comment by daveaglick** [comment]
Ah, nevermind, noticed that it was just merged to master a few minutes ago. Probably finishing up the build and deployment now. I'll sit tight and check again in a few minutes.

**Comment by devlead** [comment]
Just pushed to master,  develop had xml fixes at least.

**Comment by daveaglick** [comment]
I was right on time, looks like deploy is finished. Verifying those outstanding issues now.

**Comment by devlead** [comment]
Looking good to me👍

**Pull request merged**
