### PR TITLE
Add targeted Cake version in YAML files

### LINKED ISSUE #1277: Add targeted Cake version in YAML files
Adding the `TargetCakeVersion` property.

### PR DESCRIPTION
**Pull request by Jericho**
This pull request was created by a tool: Cake.AddinDiscoverer version 3.54.1

Resolves #1277

### CODE REVIEW

**Comment by Jericho** [comment]
Looks like this is the last batch

**Review by pascalberger — APPROVED** [review]
LGTM

**Comment by Jericho** [comment]
After this PR is merged, I will promptly release new version of AddinDisco. Going forward, it will raise one issue and one PR for each change in a YAML file instead of batching 75 changes together.

**Comment by pascalberger** [comment]
@Jericho your changes have been merged, thanks for your contribution 👍

**Pull request merged**
