### PR TITLE
Add information about break directive

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Comment by gep13** [comment]
@patriksvensson @devlead also this one. Thanks!

**Comment by patriksvensson** [comment]
Should we add that `#break` will be ignored by Cake if no debugger is attached like @devlead suggested in the other PR as well?

**Comment by gep13** [comment]
>@patriksvensson said...
Should we add that #break will be ignored by Cake if no debugger is attached like @devlead suggested in the other PR as well?

Yes, this makes sense.  I have added this here as well.

**Comment by patriksvensson** [comment]
@gep13 Ok, then I'll merge this as well :+1:

**Comment by gep13** [comment]
@patriksvensson if you want to merge this one first, then I will do a final rebase on the debug blog post PR.

**Comment by patriksvensson** [comment]
@gep13 Yes, just waiting for the CI to finish.

**Pull request merged**
