### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by NikhilKumar-coder**

### CODE REVIEW

**Review by pascalberger — COMMENTED** [review]
This change isn't required, or requested, as such, I am going to close it out.

If this change is related to Hacktoberfest, then please reach out via our Gitter channel, as there are likely places where we are looking for help.

**Comment by alexellis** [comment]
Good to see Derek in action here @pascalberger 👍

**Comment by pascalberger** [comment]
@alexellis Shouldn't the `no_newbies` rule have been kicked in here? It is [enabled](https://github.com/cake-build/website/blob/master/.DEREK.yml#L15)

**Comment by alexellis** [comment]
I think so. I'll look into it.

**Comment by alexellis** [comment]
Can you try a PR to https://github.com/openfaas/org-tester ? but give a description in the PR

**Pull request closed without merging**
