### PR TITLE
[WIP] Added FAQ section

### PR DESCRIPTION
**Pull request by gep13**
- Including new top level menu item

### CODE REVIEW

**Comment by gep13** [comment]
@cake-build/cake-team what do you think of the following idea?

image

The idea being that this page is just a flat list of questions, with either the answer in line on the page, or providing a link off to other places on the site, or externally.

@daveaglick I thought Wyam now included the ability to create an anchor for headings in a markdown file.  Is that something that I need to "enable"?  Thanks.

Inspiration for this has been borrowed from this page:

https://chocolatey.org/faq

**Comment by patriksvensson** [comment]
I like the idea as well! 👍

**Comment by gep13** [comment]
OK, so assuming I can get the question answered by @daveaglick we should be in a position to move forward with this new section of the website.

@cake-build/cake-team start thinking about common questions that we can get added onto this page.  I see it getting updated regularly.

**Comment by daveaglick** [comment]
@gep13 I'm pretty sure the anchors are added automatically now - you shouldn't need to enable them. You'll still need to create the links to those anchors though - there's no automatic table of contents thing yet.

Are the anchors not being generated here? If not, I'll pull down this PR and take a look.

**Comment by gep13** [comment]
@daveaglick I could be completely off, but I don't think they were created.  I didn't actually check the source of the page though.  I was solely going on the basis of there not being an anchor icon displayed when you hovered over the header.

I am using a plugin for MarkdownMonster which helps with the creation of the table of contents.

Could you pull this down and make sure that I am not going nuts?

**Comment by gep13** [comment]
@daveaglick any chance you can have a look at this?  Would be great to get this section of the website started.  Thanks!

**Comment by daveaglick** [comment]
👍 sounds like a job for the hackathon tomorrow

**Comment by gep13** [comment]
@daveaglick perfect!  I am sure that @devlead will be around to help out as well.  Thanks!

**Comment by daveaglick** [comment]
Don't merge this PR - I hosed it by creating a merge commit and I can't back it out since I don't have push rights. I opened #516 to take it's place with my additional enhancements.

**Comment by gep13** [comment]
@daveaglick thanks for taking a look at this!

**Pull request closed without merging**
