### PR TITLE
add Cake.Yarn AddIn

### PR DESCRIPTION
**Pull request by MilovanovM**
Support for [yarn](https://yarnpkg.com/) package manager

### CODE REVIEW

**Comment by gep13** [comment]
@MilovanovM wow, thanks for creating the Cake.Yarn addin, and for creating this Pull Request.

I will review it later and get it merged in.

While you are here, would you be in a position to add the cake-contrib user as a co-owner of the package on NuGet.org?  The reason for this was discussed here: http://cakebuild.net/blog/2016/08/cake-contribution-organization and you will see that almost all addin maintainers have added the cake-contrib user to their packages.

Please let me know if you have any questions.

**Comment by MilovanovM** [comment]
@gep13 no problem, I've added the user

**Comment by gep13** [comment]
@MilovanovM nice one, thank you very much!

**Comment by gep13** [comment]
@MilovanovM I have just checked, and based on the fact that you did this work on your clone in the develop branch, it makes it very difficult to update this PR to correct the merge conflict that is now in place.

Would you be able to re-do these changes on a separate branch, and then submit a new PR?

You can see more about this in the contributing document that we keep here: https://github.com/cake-build/cake/blob/develop/CONTRIBUTING.md

Thanks!

**Comment by MilovanovM** [comment]
@gep13 the PR is ready https://github.com/cake-build/website/pull/202
Thanks for your help!

**Comment by MilovanovM** [comment]
I'm closing out this PR

**Pull request closed without merging**
