### PR TITLE
GH617: Optmize addin downloading

### LINKED ISSUE #617: Investigate optimize addin downloading

### PR DESCRIPTION
**Pull request by devlead**
* fixes #617

### CODE REVIEW

**Comment by devlead** [comment]
Initial test about 3 minutes quicker
image

and about 100MB addins fetched instead of like GB.

Think 1-2 addins could skipped because they lack framework moniker, rather see this fixed in those potential addins.

Azure DevOps failes becuase posix build, this is a known issue with many open files in Wyam, reported Wyamio/Wyam#805

Windows build succeeds though, which is what's.
image

**Comment by devlead** [comment]
@cake-build/cake-team updated Cake.DotNetTool.Module module to 0.2.0 and disabled macOS / Linux builds for now. Ready for review.

**Comment by gep13** [comment]
@devlead I have no objections to this, but perhaps a final review from @daveaglick needed before merging?

**Comment by gep13** [comment]
This gets my...

**Pull request merged**
