### PR TITLE
Add Cake.MSBuildTask addin

### PR DESCRIPTION
**Pull request by marcosnz**

### CODE REVIEW

**Comment by marcosnz** [comment]
Thanks @patriksvensson. Will the addin show when next build is released?

**Comment by patriksvensson** [comment]
@marcosnz No problem! :smile:

**Comment by patriksvensson** [comment]
@marcosnz Btw; I saw that you have really good documentation for your addin. We could always add it to the Cake website documentation if you want to.

**Comment by marcosnz** [comment]
@patriksvensson, yes I was going to ask - what are the steps to get it included?

**Pull request merged**
