### PR TITLE
Add redirects for every OS

### PR DESCRIPTION
**Pull request by pascalberger**
Add additional redirects for every OS & runner

### CODE REVIEW

**Comment by gep13** [comment]
@pascalberger why are these necessary?

If I recall correctly, the original osx/windows/linux URL's were used for a while, but they were then replaced with the powershell/bash ones.  Those original redirects were left in place in case anyone was using them, but everywhere that we "owned" starting using the powershell/bash links.

**Comment by pascalberger** [comment]
> @gep13 said...
> If I recall correctly, the original osx/windows/linux URL's were used for a while, but they were then replaced with the powershell/bash ones. Those original redirects were left in place in case anyone was using them, but everywhere that we "owned" starting using the powershell/bash links.

Currently in docs the OS ones are used for .NET Framework (https://cakebuild.net/docs/running-builds/runners/cake-runner-for-dotnet-framework#bootstrapping-for-cake-runner-for.net-framework). We should either provide OS redirects for every bootstrapper, or adopt docs to use PowerShell / Bash redirects. I'm also OK to update docs to move away from the OS redirects.

**Comment by gep13** [comment]
Hmm, ok, fair enough.  In which case, this makes sense.

**Review by gep13 — APPROVED** [review]
LGTM!

**Pull request merged**
