### PR TITLE
Improve Docs

### PR DESCRIPTION
**Pull request by tb-rules10**
I hope u will consider my request. I'm learning these things . This one is my first pull request

### CODE REVIEW

**Comment by patriksvensson** [comment]
This change isn't required, or requested, as such, I am going to close it out.

If this change is related to Hacktoberfest, then please reach out via our Gitter channel, as there are likely places where we are looking for help.

**Review by pascalberger — APPROVED** [review]

**Comment by pascalberger** [comment]
@tb-rules10 your changes have been merged, thanks for your contribution 👍

**Comment by tb-rules10** [comment]
please add hacktoberfest-accepted label.
if my pr is merged will i need this label to be counted in hacktoberfest 2020??

**Comment by pascalberger** [comment]
This PR should count towards Hacktoberfest, see https://hacktoberfest.digitalocean.com/hacktoberfest-update. If you have any further questions please contact Digital Ocean which are organizing Hacktoberfest since we don't have any additional information.

**Comment by tb-rules10** [comment]
ok, thanks a lot .

**Pull request merged**
