### PR TITLE
Update a presentation link due to Docs.com end of service

### PR DESCRIPTION
**Pull request by Ky7m**
Sorry for the inconvenience.
Presentation has been migrated to personal OneDrive. 
More details about Docs.com end of service  - https://support.office.com/en-us/article/Important-information-about-Docs-com-end-of-service-3b0d4877-1643-457c-9756-8caf28b94da4?ui=en-US&rs=en-US&ad=US

### CODE REVIEW

**Comment by devlead** [comment]
Just FYI this will likely require a MSAcount, I get this when I click the link, it does work after I login.
image

Perhaps you could look at [Slideshare](https://www.slideshare.net/) or [Slides](https://slides.com/)

Example presentations using these services
http://slides.com/pitermarx/cake
https://www.slideshare.net/PatrikSvensson14/cake-66612025

If you prefer OneDrive that's fine by me and I'll merge, just let me know how you wish to proceed.

**Comment by Ky7m** [comment]
It is a very interesting behavior, because I have verified again in private mode and it did not ask anything 
screen shot 2017-06-19 at 11 52 13 pm

Could you check in private mode, please?

Thanks in advance!

**Comment by devlead** [comment]
InPrivate mode works, so issue likely if someone is logged into a Azure AD and not MS Account.

**Comment by Ky7m** [comment]
Moved to SlideShare/update PR. I think it is more convenient for all.

**Comment by devlead** [comment]
@Ky7m ok! I'll merge as soon as possible after CI finishes.

**Comment by Ky7m** [comment]
@devlead thanks a lot

**Comment by devlead** [comment]
@Ky7m  your changes have been merged, thanks for your contribution 👍

**Pull request merged**
