### PR TITLE
[TESTING, DO NOT MERGE] Update YAML files

### LINKED ISSUE #547: [TESTING, PLEASE IGNORE] Synchronizing YAML files
The Cake.AddinDiscoverer tool has discovered discrepencies between the YAML files currently on Cake's web site and the packages discovered on Nuget.org:

YAML files to be deleted:

YAML files to be created:
- Cake.Android.AvdManager
- Cake.ArtifactDrop
- Cake.AWS.Lambda
- Cake.AzCopy
- Cake.AzureBlobStorage
- Cake.Bower
- Cake.CachedNpm
- Cake.CakeBoss
- Cake.CK.Pack
- Cake.ClickTwice
- Cake.ConventionalChangelog
- Cake.Coverlet
- Cake.Deploy.Azure.Authentication
- Cake.Deploy.Bot.LUIS
- Cake.Deploy.Variables
- Cake.DeployParams
- Cake.DocCreator
- Cake.DocumentDb
- Cake.Eazfuscator.Net
- Cake.Flyway
- Cake.FtpDeploy
- Cake.GitHubUtility
- Cake.Gradle
- Cake.Graph
- Cake.Handlebars
- Cake.HandlebarsDotNet
- Cake.Helm
- Cake.HgVersion
- Cake.Jira
- Cake.Karma
- Cake.LittleHelpers
- Cake.Mage
- Cake.Markdown-Pdf
- Cake.MonoApiTools
- Cake.Netlify
- Cake.NewRelic
- Cake.Npx
- Cake.NSpec
- Cake.NSwag.Console
- Cake.OssIndex
- Cake.Packages
- Cake.PickAndRoll
- Cake.PinNuGetDependency
- Cake.ScheduledTasks
- Cake.SimpleHTTPServer
- Cake.SimpleVersionIncrement
- Cake.SquareLogo
- Cake.Storm.Android
- Cake.Storm.Environment
- Cake.Storm.Fluent
- Cake.Storm.Fluent.Android
- Cake.Storm.Fluent.DotNetCore
- Cake.Storm.Fluent.iOS
- Cake.Storm.Fluent.NuGet
- Cake.Storm.Fluent.Transformations
- Cake.Storm.iOS
- Cake.Storm.JsonBuildConfiguration
- Cake.Storm.Nuget
- Cake.TravisCI
- Cake.Umbraco.PackageUploader
- Cake.UncUtils
- Cake.UServer
- Cake.Utility
- Cake.ViewCompiler
- Cake.WindowsAppStore
- Cake.Xamarin.Binding.Util

YAML files to be updated:
- Cake.ActiveDirectory
- Cake.AliaSql
- Cake.Apigee
- Cake.AppleSimulator
- Cake.AWS.CloudFront
- Cake.AWS.CodeDeploy
- Cake.AWS.EC2
- Cake.AWS.ElasticLoadBalancing
- Cake.AWS.Route53
- Cake.AWS.S3
- Cake.Bumpy
- Cake.Chutzpah
- Cake.CMake
- Cake.CodeAnalysisReporting
- Cake.Compression
- Cake.Coveralls
- Cake.CsvHelper
- Cake.DocFx
- Cake.Docker
- Cake.DotNetCoreEf
- Cake.EntityFramework
- Cake.ExtendedNuGet
- Cake.FluentMigrator
- Cake.Gem
- Cake.Genymotion
- Cake.Git
- Cake.Gitter
- Cake.Grunt
- Cake.Gulp
- Cake.HipChat
- Cake.HockeyApp
- Cake.Hosts
- Cake.Http
- Cake.IIS
- Cake.ImageOptimizer
- Cake.Issues
- Cake.Issues.DocFx
- Cake.Issues.EsLint
- Cake.Issues.InspectCode
- Cake.Issues.Markdownlint
- Cake.Issues.PullRequests
- Cake.Issues.Reporting
- Cake.Issues.Reporting.Generic
- Cake.Issues.Testing
- Cake.Kudu
- Cake.Kudu.Client
- Cake.MicrosoftTeams
- Cake.MobileCenter
- Cake.MSBuildTask
- Cake.MsDeploy
- Cake.Npm
- Cake.OctoDeploy
- Cake.Openshift
- Cake.Paket
- Cake.Plist
- Cake.Powershell
- Cake.ProGet
- Cake.ProjHelpers
- Cake.Putty
- Cake.Raygun
- Cake.ReSharperReports
- Cake.Services
- Cake.Slack
- Cake.SqlServer
- Cake.SqlTools
- Cake.Terraform
- Cake.Tfx
- Cake.Topshelf
- Cake.Twitter
- Cake.VersionReader
- Cake.VsCode
- Cake.VsixSignTool
- Cake.VsMetrics
- Cake.WebDeploy
- Cake.Webpack

### PR DESCRIPTION
**Pull request by Jericho**
Resolves #547

### CODE REVIEW

**Comment by Jericho** [comment]
I just noticed that categories need two dashes like this:
```
-- AWS
-- Deployment
```

But currently the audit tool is generating YAML with only a single dash like this:
```
- Amazon
```

**Comment by Jericho** [comment]
Build is failing and I don't know what this error mean:
```Cake.exe : Unable to resolve dependencies. 'runtime.osx.10.10-x64.CoreCompat.System.Drawing 1.0.0' is not compatible with 'Cake.SquareLogo 0.8.0 constraint: runtime.osx.10.10-x64.CoreCompat.System.Drawing (>= 5.4.0-r8)'.
At line:1 char:1
+ & "C:\projects\website\tools\Cake\Cake.exe" "build.cake" -target="App ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unable to resol...(>= 5.4.0-r8)'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
An error occurred when executing task '
GetAddinPackages
'.
```

**Comment by gep13** [comment]
Going to need to bring in @daveaglick on this one.

Thoughts on why the dependencies of the Cake.SquareLogo addin are causing problems.  It is due to the base image in AppVeyor that we are running the build on?

**Comment by Jericho** [comment]
@daveaglick can you help us figure out why the build of the Cake web site is failing?

**Comment by Jericho** [comment]
@daveaglick yes it solved the problem thanks.

The current audit tool logic is: add `Prerelease: "true"` in the YAML files if (and only if) the addin package itself is marked as prerelease. Should I improve the logic to also `Prerelease = "true"` if any of the package dependencies are prerelease?

**Comment by Jericho** [comment]
A new build completed while I was typing my previous comment and it failed with a new error:
```
Executing pipeline "RenderApi" (18/26) with 1 child module(s)
            Exception while processing document System in module Razor: Illegal characters in path.
            Exception while processing document Cake.SquareLogo in module Razor: Illegal characters in path.
            Error while executing module Razor
        Error while executing module If
    Error while executing pipeline RenderApi
```

**Comment by daveaglick** [comment]
> if any of the package dependencies are prerelease?

Yeah, not a bad idea. That shouldn’t really happen in practice because prerelease status is supposed to be transitive, but this package proves that you can get around that (probably by directly editing metadata). Might get tricky though since to do it right you’d need to crawl all nested package references. If you’re not already set up to do that, might be easier to stick with the original logic and just add an exception for this one since it’s probably a corner case.

**Comment by daveaglick** [comment]
I’ll take a look at the new error - might take a little longer to diagnose though...

**Comment by devlead** [comment]
`Microsoft.Rest.ClientRuntime.Azure` are we indexing something we aren't supposed to? Any weird search paths in yml?

**Comment by Jericho** [comment]
How can we figure out which yml file is triggereing this error? There are more than 200 files.

**Comment by devlead** [comment]
I would start with the azure ones. But if one can repro loyally, then one could do a script that adds a file and executes until it fails.

**Comment by Jericho** [comment]
In the case of the error I posted 2 days ago I'm guessing the problem was triggered by Cake,SquareLogo.yml because the error message says `Exception while processing document Cake.SquareLogo in module Razor`. 

In this instance, the yml file contains: https://github.com/cake-build/website/pull/548/files#diff-93f97b91d8c22902489c027ad8427b50

Nothing seems obviously wrong to me

**Comment by Jericho** [comment]
@devlead , @daveaglick , @gep13 

I am using PR #550 as my testing ground for this error. I am trying to narrow down which yml files are causing this problem by removing several dozen files at a time and I reproduced the `Illegal characters in path` error [here](https://ci.appveyor.com/project/cakebuild/website/build/1.0.1584#L409) and [here](https://ci.appveyor.com/project/cakebuild/website/build/1.0.1585#L309)

I finally had a [successful build](https://ci.appveyor.com/project/cakebuild/website/build/1.0.1586) when I only had 27 yml files left. I started adding some of the yml files back and had a few successful builds [here](https://ci.appveyor.com/project/cakebuild/website/build/1.0.1587) and [here](https://ci.appveyor.com/project/cakebuild/website/build/1.0.1588) albeit with some weird warning:
```
    Executing pipeline "RenderApi" (18/26) with 1 child module(s)
                Multiple documents output to api/Cake.Talend.Models/Executiontime/index.html (this probably wasn't intended):
  Cake.Talend.Models.TalendApiResponse.Executiontime
  Cake.Talend.Models.Executiontime
```

but the build failed again [here](https://ci.appveyor.com/project/cakebuild/website/build/1.0.1589#L309).

As you can see from the error messages in the multiple failed builds, the yml that seems to be causing this failure is different each time. In fact, sometimes the error message refer to a "document" that doesn't seem to correspond to a yml file at all. Case in point: the error message in the last failure refers to `MagicChunks.Helpers` and `Cake.Common.Build.Jenkins`, which look to me like dependencies to some other packages.

**Comment by daveaglick** [comment]
@Jericho Nice detective work - I'll take a closer look when I get a chance (though might not be until early next week - on vacation with the family this week).

**Comment by daveaglick** [comment]
My first instinct is that multiple packages have symbols that Wyam isn't correctly converting to a valid file name for the output documentation file for that symbol. That's why it seems random - Wyam processes the assemblies in parallel so if more than one has a symbol for which we can't generate a valid file path, then it'll be random which one blows up on each build. So now the question is: what kind of symbol is Wyam having trouble with?

**Comment by daveaglick** [comment]
Gotcha! The symbol display name (which is used to calculate the HTML path for the doc file for this symbol) is `<StartupCode$Cake-SquareLogo>` which clearly has some invalid characters and isn't a valid path:

2018-07-26_18h10_39

2018-07-26_18h11_47

2018-07-26_18h14_06

Unfortunately I have absolutely no idea what this symbol is or why it's named like that. I've never seen this kind of symbol name before. It'll require a little more research to figure out what I'm actually looking at here.

**Comment by Jericho** [comment]
Uneducated guess on my part: could it be associated with the fact that some authors ILMerge dependencies in their addin? I don't know if this particular adin merges other dependencies, I'm just mentioning it because this situation has caused me some headaches when programatically processing some addins.

**Comment by daveaglick** [comment]
cc @vcsjones

**Comment by vcsjones** [comment]
> Unfortunately I have absolutely no idea what this symbol is or why it's named like that.

F# compiler.😀

**Comment by daveaglick** [comment]
Thanks @vcsjones!

So that means Wyam needs to check for goofy auto generated F# symbols and probably just exclude them. I can probably put in a temporary workaround into the config file for this site, but Wyam itself will need a better fix upstream (at which point the fix here can be removed).

**Comment by gep13** [comment]
Okay, so this is a new one on me....

Looks like this addin is actually written in F#:

https://github.com/wk-j/square-logo/tree/master/src/Cake.SquareLogo

**Comment by Jericho** [comment]
I’m sure it’s not the only one. There are most likely others as well.w

**Comment by daveaglick** [comment]
> I can probably put in a temporary workaround into the config file for this site

Narrator: "He could not."

Turns out this needs to be fixed inside the Wyam CodeAnalysis extension. So that's the bad news: you'll need to wait for a new Wyam release. The good news is that I'm trying really, really hard to get that out the door early next week (I mean it this time! Really!).

Once the new version of Wyam is released, I'll send a PR to update this repo. Then once that's merged, you can rebase this PR (and #550) and you should be good to go.

**Comment by Jericho** [comment]
Sounds really good!

FYI: this PR is just a test run of new functionality in AddinDiscoverer, not a PR I intend to commit. When this issue is resolved and we can show that cake's website can successfully build I will delete this PR (and any other test runs that might still be open), publish new release of AddinDiscoverer and let it automatically synchronize all YAML files.

**Comment by Jericho** [comment]
Thanks to @daveaglick for resolving the issue in Wyam with F# libraries. I don't have permission to trigger a re-build of this PR so I simply created a [new PR](https://github.com/cake-build/website/pull/563) which built successfully.

**Pull request closed without merging**
