### PR TITLE
(GH-43) Add team page

### PR DESCRIPTION
**Pull request by pascalberger**
Add a page for presenting the core team. Order is randomized on every generation.

@cake-build/cake-team I added GitHub, Twitter and website for everybody. If you want to have futher links added (code is currently there for LinkedIn) add a comment.

image

Fixes #43

### CODE REVIEW

**Comment by gep13** [comment]
@pascalberger my LinkedIn id should just be `gep13`.  Happy for you to add this as well.

**Review by gep13 — APPROVED** [review]
This looks great, thanks for getting this added!

**Comment by mholo65** [comment]
Great! 

Dunno, what LinkedIn id is... But my "short" url is https://www.linkedin.com/in/martin-bjorkstrom

So maybe id is `martin-bjorkstrom`?

**Comment by daveaglick** [comment]
Love this, great work @pascalberger!

**Review by daveaglick — APPROVED** [review]

**Review by augustoproiete — APPROVED** [review]

**Review by devlead — APPROVED** [review]
LGTM 👍

**Comment by augustoproiete** [comment]
@pascalberger LinkedIn: `augustoproiete`

**Comment by nils-a** [comment]
@pascalberger linkedin is `nils-andresen-hamburg`

**Comment by ecampidoglio** [comment]
@pascalberger My LinkedIn ID is `ecampidoglio`.

**Comment by patriksvensson** [comment]
My LinkedIn username is `psvensson82`

**Pull request merged**
