### PR TITLE
Add new Cake.Vagrant addin docs

### PR DESCRIPTION
**Pull request by agc93**
Adding docs for my new [Cake.Vagrant addin](https://github.com/agc93/Cake.Vagrant)

### CODE REVIEW

**Comment by gep13** [comment]
@agc93 wow, you have been busy! :smile:

**Comment by gep13** [comment]
@agc93 out of interest, where are you hosting/deploying the docfx documentation?

**Comment by agc93** [comment]
Planning on putting it in the repo's GitHub Pages repo, just haven't gotten around to it yet.

**Comment by gep13** [comment]
noice. Will be interesting to see the outcome of that.  I am currently using ReadTheDocs for hosting the docs for mine, but I have been thinking "again" about switching to something.  My immediate thought had been to use Wyam, just need to get the cycles to figure out the best approach there.  I like ReadTheDocs, as you can easily version the docs for different versions of the tools in question.

**Comment by agc93** [comment]
Yeah I really like the look of Wyam and am probably going to cut one of my other non-Cake projects on to it as a test-bed. I just love DocFx's apidoc support. Just turn on XML Generation in the project and bam basically MSDN.

I always found RtD to be that little bit too confusing to set up, personally. So I've now got the full spectrum of my own [very basic tool](https://github.com/agc/DocCreator), [Wyam](http://wyam.io), or [DocFx](http://dotnet.github.io/docfx) for serious doco. The times we live in :P

**Pull request merged**
