### PR TITLE
Add blog post about debugging Cake scripts in Visual Studio Code

### PR DESCRIPTION
**Pull request by mholo65**
@gep13 As discussed on Gitter

@patriksvensson there's something odd with the Markdown parsing when having indented ```code``` in a list. Website doesn't render same as e.g. preview in VS Code or other tools.

Github seems to also render OK! (see below):

1. Test

    ``` json
    {
        "example" : 1
    }
    ```
1. Test

### CODE REVIEW

**Comment by mholo65** [comment]
Also, I'm mentioning debugging in Linux / Mac... (But have not verified) :smile: Do any of you happen to know if it works?

**Comment by patriksvensson** [comment]
@mholo65 No idea, but we better verify this. My girlfriend has a mac, perhaps I can verify sometime this week.

**Comment by mholo65** [comment]
@patriksvensson as said in blog post, you can find working example here https://github.com/mholo65/cake-vscode-debug-example

Feel free to add ```build.sh``` bootstrapper :smile:

**Comment by mholo65** [comment]
@patriksvensson @gep13 FYI, tested debugging on Linux yesterday and worked as expected. :+1:

**Comment by gep13** [comment]
@mholo65 while you are here...

Have you seen any issues with getting watched variables to show their content? I have created a new NuGetPackSettings class, set some properties on it, debugged the script using the contents of this blog post, and an exception is thrown when trying to inspect the variable.  Have you seen similar?

**Comment by gep13** [comment]
@mholo65 this is what I am seeing when I try to debug...

image

**Comment by mholo65** [comment]
@gep13 Aah, haven't seen that, but haven't tested it that much. I'll investigate later tonight. Might be something with how the libs are compiled with dotnet cli.. Might also be that you are using "light theme" (my eyes hurt) :smile:

**Comment by mholo65** [comment]
@gep13 able to reproduce and seeing this also in Visual Studio.. Tried enabling [portable PDBs](https://github.com/OmniSharp/omnisharp-vscode/wiki/Portable-PDBs) for Cake.Common, Cake.Core and Cake, but didn't work... Need to dig deeper..

**Comment by devlead** [comment]
@mholo65 yeah came to the same conclusion, strangely for me I can watch Cake/Cake.Core types i.e. cake context. It's just Cake.Common that give me trouble.

**Comment by mholo65** [comment]
@devlead yep, verified same. E.g. watching **DirectoryPath** works, but not **NuGetPackSettings**...

**Comment by gep13** [comment]
@mholo65 are you in a position to update this blog post?  Did you try out the new VsCode extension? Thanks!

**Comment by mholo65** [comment]
@gep13 yep, I'm in position to update, hopefully later today. I've not yet had time to update. I see that you are now in position to release v0.16.0, making this blog post high priority (at least for me :smile:)

Also had some problem with the markdown rendering, as mentioned in [first comment](https://github.com/cake-build/website/pull/142#issue-171989799). Problem is inline/indented code snippets in ordered lists. Works well on "other" markdown rendering engines, but not in Cake Website.

**Comment by gep13** [comment]
@mholo65 0.16.0 has been pushed to NuGet already, just waiting on blog post about it to be finalised 🙂

It is unlikely that we will change the markdown engine of the site as it currently is, since we are discussing how we can move it to another platform. Can you modify the content of the post to workaround the limitation?

**Comment by gep13** [comment]
@mholo65 oh, and obviously, thanks for your help/contribution!

**Comment by mholo65** [comment]
@gep13 yep, I could try... One simple approach is to switch to unordered lists and not have the ```code``` indented...

**Comment by mholo65** [comment]
@gep13 updated.. But we'll have to wait for **v0.16.1** until it works.

**Comment by gep13** [comment]
@mholo65 Cake 0.16.1 has been released, which should correct the issue that you were seeing.  Can you confirm? Thanks!

**Comment by mholo65** [comment]
@gep13, nice! Will do later tonight!

**Comment by mholo65** [comment]
@gep13 Updated, works as expected with Cake 0.16.1 and latest VS Code extension.

**Comment by gep13** [comment]
>@mholo65 said...
@gep13 Updated, works as expected with Cake 0.16.1 and latest VS Code extension.

Nice one! Thanks for getting that updated!

**Pull request merged**
