### PR TITLE
Restructure documentation

### PR DESCRIPTION
**Pull request by pascalberger**
Restructure documentation. The idea is to split documentation into separate chapters for different stakeholders: Users which are running builds, developers writing build scripts and developers which are extending cake.

There are a few changes in the pages to fit to the new structure. But mostly only moves pages around. Content can be updated in subsequent PRs.

For existing URLs redirectes should be generated.

## Before this PR:

image

## After this PR:

image

Most of the fundamentals topics have been moved to `Running Builds` and `Writing Builds`. Idea is to add more general topics here explaining the philosophy behind Cake (dependency based programming, etc).

image

image

image

image

### CODE REVIEW

**Comment by daveaglick** [comment]
I _love_ it - the new top-level sections seem a lot clearer to me

**Comment by pascalberger** [comment]
Not done here is creating a "Community" section as described here: https://github.com/cake-build/website/issues/928#issuecomment-702558183. This will be done as part of https://github.com/cake-build/website/issues/928 (probably moving the Contributing and Resources section into a new `/community` page)

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by pascalberger** [comment]
Azure Pipelines seems to have some issues. Build was successful but status was not reported back: https://dev.azure.com/cake-build/website/_build/results?buildId=12886&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b.

If PR is OK we can merge without build status.

**Comment by gep13** [comment]
I would say go for it!

**Comment by patriksvensson** [comment]
Must say that I think the restructering is much better! 👍

**Comment by devlead** [comment]
> Azure Pipelines seems to have some issues. Build was successful but status was not reported back: https://dev.azure.com/cake-build/website/_build/results?buildId=12886&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b.
> 
> If PR is OK we can merge without build status.

Azure had an major outage yesterday.

LGTM 👍

**Pull request merged**
