### PR TITLE
Update Cake.RepoVersion.yml

### PR DESCRIPTION
**Pull request by kjjuno**
Cake.RepoVersion is being transferred to the cake-contrib organization

### CODE REVIEW

**Comment by kjjuno** [comment]
This change was originally submitted about a week ago, but I have not yet seen Cake.RepoVersion show up in the addin list on this site https://cakebuild.net/addins/

How often is this list updated? Is there something else I needed to do in order to get this addin listed?

**Comment by gep13** [comment]
@kjjuno you can see your addin listed on the develop version of the site here:

https://develop.cakebuild.net/addins/

Looks like we need to bump this over to the production site.  I will do this once we merge this PR, which needs to wait until I transfer the repository into the Cake Contrib Organisation.

**Comment by gep13** [comment]
@kjjuno the initial transfer of the repository to the Cake Contrib GitHub Organisation is complete.  I will set up an AppVeyor project for the repository as well, simply because all other repositories in this Organisation have one.  I notice that you have other CI services configured, and that is fine, no harm in having multiple setup.  We have a tool that runs that configures permissions in AppVeyor, but that takes a little while to run.  Once complete, you will be able to access the AppVeyor project by logging in with your GitHub account.

**Comment by kjjuno** [comment]
AppVeyor is just fine. I have things currently configured to only push to nuget.org when I push a tag. I would like to maintain that functionality.

**Comment by kjjuno** [comment]
AppVeyor is just fine. I have things currently configured to only push to nuget.org when I push a tag. I would like to maintain that functionality.

**Comment by gep13** [comment]
@kjjuno that is similar to how I build most of my own personal addins, but I make use of Cake.Recipe to make that happen, but there is no requirement for you to use that.  You should be able to configure things how you need them, but if not, we can definitely get things set up for you.  I will let you know when all permissions have finished syncing.

Also, do you use Slack/Twitter?  Would be good to follow you from the Cake-Contrib Twitter account, and also to invite you to the Cake-Contrib Slack team where you can ask any questions about anything for this addin, or Cake in general.

**Comment by kjjuno** [comment]
I use slack, and I have twitter, but I almost never use it.

**Comment by gep13** [comment]
@kjjuno can you let me know those details?  I am gep13 on twitter if you wanted to DM them to me (my DM's are open).  That way I can get you invited to the Slack Team

**Comment by gep13** [comment]
@kjjuno the latest version of the Cake Website has now been published with your changes in it.

**Pull request merged**
