### PR TITLE
New Blog Post Cake.Paket

### PR DESCRIPTION
**Pull request by larzw**
Hi!

This is a guest blog post for [Cake.Paket](https://github.com/larzw/Cake.Paket). As per the request https://github.com/larzw/Cake.Paket/issues/1 , it's an introduction to the addin and module.

Thanks!

### CODE REVIEW

**Comment by larzw** [comment]
I'm not sure why appveyor failed?

**Comment by devlead** [comment]
@larzw regarding the build fail, not a 100% sure yet, might have to run that by @daveaglick, but it's only this blog post that fails, checkout develop and that builds fine. WIll see if I can do some debugging later.

**Comment by gep13** [comment]
>@larzw said...
I'm not sure why appveyor failed?

The problem here is this:

`title: Cake.Paket: An Addin and Module to Add Support for Paket in Cake`

and you change it to this:

`title: Cake.Paket - An Addin and Module to Add Support for Paket in Cake`

The extra `:` is throwing off the yaml parser.

Also, can you change the name of the file to:

`2017-01-23-cake-paket.md`

**NOTE:** The padded 0 in the month.

**Comment by gep13** [comment]
>@devlead said...
WIll see if I can do some debugging later.

Tested the above locally on my machine, and build works after making the two changes.  Previously, the build of the PR was failing locally for me too.

**Comment by devlead** [comment]
@gep13 great 👍

**Comment by larzw** [comment]
Thanks for the help @gep13 and @devlead.

- Added padded 0 to the month in the file name.
- Added introduction of myself to the bottom of the blog.
- Removed colon in the blog title and replaced with dash.

I like the new website too!

**Comment by gep13** [comment]
@larzw thank you very much for doing this blog post, and for creating Cake.Paket in the first place!

**Pull request merged**
