### PR TITLE
VSTS - .Net Standard Library,  using Cake with a powershell script

### PR DESCRIPTION
**Pull request by StefanOssendorf**
Hello, 

since I was struggling to get cake work on the new csproj format of a .Net Standard library on VSTS, I thought I can put a small guide to fix this issue.

Maybe it can be moved to a short FAQ topic like "Resolve error 'Failed to load msbuild Toolset v14'".
I'm open for all :)

Cheers,
Stefan

Ps: I've linked the pictures to my fork, because I do not know another way. So an advice would be great!

### CODE REVIEW

**Comment by StefanOssendorf** [comment]
Should I show a diff of the complete file or what exactly do you mean? Or is there a nice way to show a diff?

**Comment by StefanOssendorf** [comment]
NuGet resoltion part changed to make the part to change more clear.

**Comment by Cheesebaron** [comment]
That diff change is much much better now. All green from here 👍

**Comment by devlead** [comment]
@StefanOssendorf  your changes have been merged, thanks for your contribution 👍

**Comment by StefanOssendorf** [comment]
@devlead You're welcome :)

**Pull request merged**
