### PR TITLE
GH283: Add docs for new addin Cake.Android.Adb

### PR DESCRIPTION
**Pull request by Redth**
New Addin: http://github.com/redth/Cake.Android.Adb

### CODE REVIEW

**Comment by gep13** [comment]
@Redth can you rebase this one?  Thanks!

**Comment by Redth** [comment]
Yes, apparently github website lets me do that too, excellent!

**Comment by gep13** [comment]
>@Redth said...
Yes, apparently github website lets me do that too, excellent!

It's not perfect, as you end up with two commits, rather than one (i.e. it isn't a true rebase) but for the purposes of the website repo, I think this is ok, however, this approach likely wouldn't be accepted on the main Cake repo.

**Comment by gep13** [comment]
Relates to #283

**Pull request merged**
