### PR TITLE
GH-1427: Add ability to sort extensions by name & publish date

### LINKED ISSUE #1427: Add possibility to sort extensions
Add possibility to sort extensions by different criterias:

- By name (default)
- By publish date

### PR DESCRIPTION
**Pull request by augustoproiete**
---

Closes #1427

### CODE REVIEW

**Review by pascalberger — APPROVED** [review]
LGTM

**Comment by pascalberger** [comment]
@augustoproiete your changes have been merged, thanks for your contribution 👍

**Comment by augustoproiete** [comment]
@pascalberger It looks like the CSS didn't get updated during the deployment (the asc/desc arrows are not being displayed). Is this something I forgot to do in the PR, or something you need to do on the deployment to force the cache purge? e.g. Set `SHOULD_PURGE_CLOUDFLARE_CACHE` env. variable?

image

**Comment by pascalberger** [comment]
Yes, this was the caching still in place. Should be fine now.

**Pull request merged**
