### PR TITLE
added Cake.Prompt

### PR DESCRIPTION
**Pull request by megakid**

### CODE REVIEW

**Comment by gep13** [comment]
@megakid before getting this merged, can you confirm whether you have spoken with the original author of Cake.Prompt before forking and pushing the NuGet package?  Was there a reason that the package never made it to NuGet.org?

**Comment by gep13** [comment]
@megakid apologies for not getting back to you sooner about this, I must have missed the notification.

Thank you for explaining.  Would you be interested in moving this addin into the Cake-Contrib Organisation, so that we can ensure the long term maintainability of the addin?

**Comment by gep13** [comment]
@devlead @asbjornu @ecampidoglio so, I "think" I see the issue here, and why the rebase plugin isn't working as expected.

The PR comes from the develop branch on the fork, not a branch on the fork, and I "think" that this is why it isn't able to rebase it.

It would be good to test this again with another PR that uses a branch, before raising any issue about what is going on here.

Thoughts?

**Comment by asbjornu** [comment]
I agree that’s worth a shot.

**Comment by megakid** [comment]
> Would you be interested in moving this addin into the Cake-Contrib Organisation, so that we can ensure the long term maintainability of the addin?

Absolutely.  How does that happen? :)

**Comment by gep13** [comment]
@megakid the entire process is documented here:

https://github.com/cake-contrib/Home#how-do-i-as-an-addin-author-transfer-a-repository-to-the-organisation

The only part that I would need you to do would be the initial transfer of the repository to my GitHub account, and from there, I can move it into the Organisation.

**Comment by megakid** [comment]
Transfer requested @gep13

**Comment by gep13** [comment]
@megakid I have now went through the process of adding this repository into the Cake-Contrib Organisation, and you should have received an email asking you to join.

Do you use Slack?  If so, can you let me know the preferred email address to send you an invite to?  Also, are you on Twitter?  If so, can you let me know your Twitter username?

Regarding this PR.. Would you be able to raise a new PR, using a branch so that we can update it with the latest changes from the source repository?  Thanks!

**Comment by megakid** [comment]
My twitter is @floydy - I don't use Slack unfortunately.

I'll raise a new PR :)

**Pull request closed without merging**
