### PR TITLE
Added Cake.SqlServer

### PR DESCRIPTION
**Pull request by trailmax**
Added a description of the new SqlServer package into list of addins

### CODE REVIEW

**Comment by gep13** [comment]
@trailmax can I get you to do something for me?

As this PR stands right now, the generated documentation looks like this:

image

Which is missing all the documentation that you put into the source code here:

image

This is due to the fact that you are not including the XML Documentation file within in the NuGet Package.  Would you be in a position to add this file into the NuGet Package, so that the documentation can be generated?

**Comment by gep13** [comment]
Raised an issue about this here: https://github.com/AMVSoftware/Cake.SqlServer/issues/3

**Comment by trailmax** [comment]
Added the missing xml file into nuget and added the reference to this file in the addins.xml.

**Comment by gep13** [comment]
@trailmax thanks for getting this added.  This is now live here: http://cakebuild.net/dsl/sqlserver

**Pull request merged**
