### PR TITLE
Create Cake.MarkdownToPdf.yml

### PR DESCRIPTION
**Pull request by twenzel**

### CODE REVIEW

**Comment by gep13** [comment]
@twenzel thank you for submitting this PR.

Just so I am clear, is this addin similar to this addin:

https://github.com/cake-contrib/Cake.Markdown-Pdf

**Comment by twenzel** [comment]
Yes similar, but working without any dependencies (like node.js/npm and the markdown-pdf package).

**Comment by gep13** [comment]
Gotcha!  Makes sense, just wanted to check.

**Comment by gep13** [comment]
@twenzel your changes have been merged, thanks for your contribution 👍

**Pull request merged**
