### PR TITLE
Update YAML files

### LINKED ISSUE #543: Synchronizing YAML files
The Cake.AddinDiscoverer tool has discovered discrepencies between the YAML files currently on Cake's web site and the packages discovered on Nuget.org:

YAML files to be deleted:

YAML files to be created:
- Cake.Android.AvdManager
- Cake.Aws.ElasticBeanstalk.Dev
- Cake.AWS.Lambda
- Cake.AzCopy
- Cake.Bower
- Cake.Bridge
- Cake.BuildSystems.Module
- Cake.CakeBoss
- Cake.CK.Pack
- Cake.ClickTwice
- Cake.ConventionalChangelog
- Cake.Deploy.Azure.Authentication
- Cake.Deploy.Azure.ResourceManager
- Cake.Deploy.Bot.LUIS
- Cake.Deploy.Variables
- Cake.DeployParams
- Cake.DocCreator
- Cake.DocumentDb
- Cake.Eazfuscator.Net
- Cake.Flyway
- Cake.FtpDeploy
- Cake.Git.NonPortable
- Cake.GitHubUtility
- Cake.Gradle
- Cake.Graph
- Cake.Handlebars
- Cake.HandlebarsDotNet
- Cake.Helm
- Cake.HgVersion
- Cake.Jira
- Cake.Karma
- Cake.LittleHelpers
- Cake.Mage
- Cake.Markdown-Pdf
- Cake.Mix
- Cake.MonoApiTools
- Cake.Netlify
- Cake.NewRelic
- Cake.Npx
- Cake.NSpec
- Cake.NSwag.Console
- Cake.NuGet
- Cake.OssIndex
- Cake.PinNuGetDependency
- Cake.Recipe
- Cake.ScheduledTasks
- Cake.Scripting.Abstractions
- Cake.Scripting.Transport
- Cake.ServiceOrchestration
- Cake.SimpleHTTPServer
- Cake.SquareLogo
- Cake.Storm.Android
- Cake.Storm.Environment
- Cake.Storm.Fluent
- Cake.Storm.Fluent.Android
- Cake.Storm.Fluent.DotNetCore
- Cake.Storm.Fluent.iOS
- Cake.Storm.Fluent.NuGet
- Cake.Storm.Fluent.Transformations
- Cake.Storm.iOS
- Cake.Storm.JsonBuildConfiguration
- Cake.Storm.Nuget
- Cake.Testing
- Cake.Tin
- Cake.TravisCI
- Cake.Umbraco.PackageUploader
- Cake.UncUtils
- Cake.UServer
- Cake.Utility
- Cake.ViewCompiler
- Cake.VSforMac
- Cake.WindowsAppStore
- Cake.Wyam.Recipe
- Cake.Xamarin.Build
- Cake.Xamarin.Build.CakeBuilder

YAML files to be updated:
- Cake.ActiveDirectory
- Cake.AliaSql
- Cake.Apigee
- Cake.AppleSimulator
- Cake.AWS.CloudFront
- Cake.AWS.CodeDeploy
- Cake.AWS.EC2
- Cake.AWS.ElasticLoadBalancing
- Cake.AWS.Route53
- Cake.AWS.S3
- Cake.Bumpy
- Cake.Chutzpah
- Cake.CMake
- Cake.CodeAnalysisReporting
- Cake.Compression
- Cake.Coveralls
- Cake.DocFx
- Cake.Docker
- Cake.DotNetCoreEf
- Cake.EntityFramework
- Cake.ExtendedNuGet
- Cake.FluentMigrator
- Cake.Gem
- Cake.Genymotion
- Cake.Git
- Cake.Gitter
- Cake.Grunt
- Cake.Gulp
- Cake.HipChat
- Cake.HockeyApp
- Cake.Hosts
- Cake.Http
- Cake.IIS
- Cake.ImageOptimizer
- Cake.Issues
- Cake.Issues.DocFx
- Cake.Issues.EsLint
- Cake.Issues.InspectCode
- Cake.Issues.Markdownlint
- Cake.Issues.MsBuild
- Cake.Issues.PullRequests
- Cake.Issues.PullRequests.Tfs
- Cake.Issues.Reporting
- Cake.Issues.Reporting.Generic
- Cake.Issues.Testing
- Cake.Kudu
- Cake.Kudu.Client
- Cake.MicrosoftTeams
- Cake.MobileCenter
- Cake.MSBuildTask
- Cake.MsDeploy
- Cake.Npm
- Cake.OctoDeploy
- Cake.Openshift
- Cake.Paket
- Cake.Plist
- Cake.Powershell
- Cake.ProjHelpers
- Cake.Putty
- Cake.Raygun
- Cake.ReSharperReports
- Cake.Services
- Cake.Slack
- Cake.SqlServer
- Cake.SqlTools
- Cake.Terraform
- Cake.Tfx
- Cake.Topshelf
- Cake.Twitter
- Cake.VersionReader
- Cake.VsCode
- Cake.VsixSignTool
- Cake.VsMetrics
- Cake.WebDeploy
- Cake.Webpack

### PR DESCRIPTION
**Pull request by Jericho**
Resolves #543

### CODE REVIEW

**Comment by Jericho** [comment]
Identified issue: Cake.BuildSystems.Module is still on this list. This is due to fact that package contains multiple DLLs and none of them match the naming convention. This leads to an exception which occurs BEFORE we identify this package as a Module.

The solution is to throw the exception AFTER we identify the package type.

**Comment by gep13** [comment]
At some point, would it be possible to do some duplicate checking? For example, the ElasticBeanStalk.Dev package is one that I would have flagged during manual process.  For example, I would have likely contacted the author of that addin and asked whether this addin was required, I.e. how does it differ from the original?

**Comment by gep13** [comment]
Also, minor point, but since we are creating an issue, can we include the issue number in the commit message, I.e. `(GH-543) Did stuff`

**Comment by Jericho** [comment]
I can certainly include issue number in commit message. I currently include it only in the PR message.

**Comment by Jericho** [comment]
I'm sure we can do dupe checking. I'm guessing the logic would be to do a partial match on the name of the addin or something similar? Can you open an issue in the AddinDiscoverer repo and explain what dedupe logic you propose?

**Comment by Jericho** [comment]
Closing this PR and related issue. Will run audit process one more time with following improvements:
- fix to properly identify Cake.BuildSystems.Module
- fix to properly identify Cake.Grunt
- improvement to include issue number in commit messages

**Comment by gep13** [comment]
@Jericho I have created an issue here:

https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/27

I have also reached out to the author of the `.Dev` package to see if we can figure out why there is a second package.

**Pull request closed without merging**
